# PyTorch Fundamentals
## 2. Tensors with Gradients

### Creating Tensor with Gradients
- A Variable wraps a Tensor
- Allows accumulation of gradients

In [1]:
import torch

In [ ]:
a = torch.ones((2, 2), requires_grad=True)
a

In [ ]:
a.requires_grad

In [ ]:
# Not a variable
no_gradient = torch.ones(2, 2)

In [ ]:
no_gradient.requires_grad

In [ ]:
# Behaves similarly to tensors
b = torch.ones((2, 2), requires_grad=True)
print("Actual Variables")
print(a)
print(b)

print("Addition")
print(a + b)
print(torch.add(a, b))

print("Multiplication")
print(a * b)
print(torch.mul(a, b))

### Manually and Automatically Calculating Gradients

**What exactly is `requires_grad`?**
- Allows calculation of gradients w.r.t. the variable

$$y_i = 5(x_i+1)^2$$

In [13]:
x = torch.ones(2, requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

$$y_i\bigr\rvert_{x_i=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20$$

In [14]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

**Backward should be called only on a scalar (i.e. 1-element tensor) or with gradient w.r.t. the variable**
- Let's reduce y to a scalar then...

$$o = \frac{1}{2}\sum_i y_i$$

In [15]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

<center> **Recap `y` equation**: $y_i = 5(x_i+1)^2$ </center>

<center> **Recap `o` equation**: $o = \frac{1}{2}\sum_i y_i$ </center>

<center> **Substitute `y` into `o` equation**: $o = \frac{1}{2} \sum_i 5(x_i+1)^2$ </center>

$$\frac{\partial o}{\partial x_i} = \frac{1}{2}[10(x_i+1)]$$

$$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{1}{2}[10(1 + 1)] = \frac{10}{2}(2) = 10$$

In [17]:
o.backward()

In [18]:
x.grad

tensor([10., 10.])

In [ ]:
x.requires_grad

In [ ]:
y.requires_grad

In [ ]:
o.requires_grad

---
# Summary
- Tensor with Gradients
    - Wraps a tensor for gradient accumulation
- Gradients
    - Define original equation
    - Substitute equation with `x` values
    - Reduce to scalar output, `o` through `mean`
    - Calculate gradients with `o.backward()`
    - Then access gradients of the `x` variable through `x.grad`